apiVersion: skaffold/v2alpha3
kind: Config
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: nice-unison-421712
  artifacts:
    - image: us.gcr.io/nice-unison-421712/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
